name: Deploy to Fly
on:
  workflow_dispatch:

jobs:
  fly:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Prepare & Deploy
        continue-on-error: true
        run: |
          #secret中FLY_APP格式为 应用名,token
          #多个FLY_APP以;分割
          APPNAME="$(echo "${{ secrets.FLY_APP }}" |sed 's#;# #g')"
          unset num
          for app in $APPNAME; do
            num=$(( num+1 ))
            NAME=$(echo $app |cut -d\, -f1)
            TOKEN=$(echo $app |cut -d\, -f2)
            sed -i "/^app /s#\".*\"#\"$NAME\"#" fly.toml
            sed -i "/AUUID/s#\".*\"#\"${{ secrets.AUUID }}\"#" fly.toml
            sed -i "/ArgoCERT/s#\".*\"#\"${{ secrets.ARGOCERT }}\"#" fly.toml
            sed -i "/ArgoJSON/s#\".*\"#\"${{ secrets.ARGOJSON }}\"#" fly.toml
            sed -i "/ArgoDOMAIN/s#\".*\"#\"${{ secrets.ARGODOMAIN }}\"#" fly.toml
            if [ $num -gt 1 ]; then
              killall flyctl
            fi
            if ! [ -d "~/.fly" ]; then
              mkdir -p ~/.fly
              echo "access_token: $TOKEN" > ~/.fly/config.yml
            fi
            if flyctl status --app "$NAME" --access-token "$TOKEN" |grep -q "running"; then
              flyctl deploy --remote-only --region "sin" --access-token "$TOKEN"
            else
              flyctl launch --copy-config --now --name "$NAME" --region "sin" --access-token "$TOKEN"
            fi
          done
